title: Your awesome title
author:
  name: Your name
  email: youremail@domain.com

header_pages:
  - work.md
  - about.md
  - contact.md

hima:
  colourscheme: 'auto'
  social:
    - { platform: github, url: 'https://www.github.com' }
    - { platform: linkedin, url: 'https://www.linkedin.com' }
    - { platform: instagram, url: 'https://www.instagram.com' }

# build settings
theme: hima

plugins:
  - jekyll-seo-tag
