title: Your awesome title
author:
  name: Your name
  email: youremail@domain.com

header_pages:
  - about.md
  - users.md

hima:
  colourscheme: auto # auto, light, dark
  social:
    - { platform: github, url: 'https://www.github.com' }
    - { platform: linkedin, url: 'https://www.linkedin.com' }
    - { platform: instagram, url: 'https://www.instagram.com' }

# build settings
remote_theme: brandoncardoso/hima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
